sudo: false
language: ruby
before_install:
  - gem update --system
  - gem install json sqlite3
  - gem --version
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1

branches:
  except:
    - gh-pages
