sudo: false
language: ruby
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
rvm:
- 2.1.10
- 2.2.5
- 2.3.1
matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.gemfile
branches:
  except:
  - gh-pages
deploy:
  provider: rubygems
  api_key:
    secure: AUJy9JSNrNcJcZc6JQErh1LtmHrdQBk1W0DYVT0soyBEx5hbKKoIympmrlh9VcZxNpbLfbuCdxl2C0nWMembwx71tLytvM76BqoU2KKTxQQLju8SUAyzGQabkNHr0mzpUDQiC4L16c5k+voCkWtptGkxiVq6eDZExBSzDM8cVMk=
  gem: acts_as_textcaptcha
  on:
    tags: true
    repo: matthutchinson/acts_as_textcaptcha
